import React,{useEffect,useState} from 'react';
import {Alert,Button,Image,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import * as ImagePicker from 'expo-image-picker';
const API=process.env.EXPO_PUBLIC_API_URL||'http://127.0.0.1:8000'; const attrs=['category','type','color','pattern','fabric','fit','style','occasion','season'];
export default function App(){const [screen,setScreen]=useState<'home'|'result'|'lab'>('home');const [uri,setUri]=useState<string>();const [result,setResult]=useState<any>();const [busy,setBusy]=useState(false);const [corrections,setCorrections]=useState<any>({});const [models,setModels]=useState<any[]>([]);useEffect(()=>{fetch(`${API}/models`).then(r=>r.json()).then(setModels).catch(()=>{})},[screen]);const modelStatus=(id:string)=>models.find(m=>m.id===id)?.status==='installed';
const pick=async(camera=false)=>{const perm=camera?await ImagePicker.requestCameraPermissionsAsync():await ImagePicker.requestMediaLibraryPermissionsAsync();if(!perm.granted)return Alert.alert('Permission needed','Allow photo access in iPhone Settings.');const r=camera?await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:0.9}):await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:0.9});if(!r.canceled){setUri(r.assets[0].uri);setResult(undefined);setScreen('result')}};
const analyze=async()=>{if(!uri)return;setBusy(true);try{const form=new FormData();form.append('file',{uri,name:'clothing.jpg',type:'image/jpeg'} as any);const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),190000);const res=await fetch(`${API}/analyze`,{method:'POST',body:form,signal:ctl.signal});clearTimeout(timer);if(!res.ok)throw new Error(await res.text());setResult(await res.json())}catch(e:any){Alert.alert('Analysis unavailable',e.name==='AbortError'?'The request timed out.':`Check the backend and Wi‑Fi connection. ${e.message||''}`)}finally{setBusy(false)}};
const saveCorrection=async(a:string)=>{if(!result||!corrections[a])return;await fetch(`${API}/corrections?image_id=${result.imageId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({attribute:a,originalAIValue:result[a],correctedValue:corrections[a]})});Alert.alert('Saved','Your correction preserves the original AI prediction.')};
if(screen==='home')return <View style={s.page}><Text style={s.title}>AI WARDROBE</Text><Text style={s.sub}>Phase 1 · local clothing vision</Text><Button title="Take Photo" onPress={()=>pick(true)}/><Button title="Choose From Photos" onPress={()=>pick(false)}/><TouchableOpacity onPress={()=>setScreen('lab')}><Text style={s.link}>Developer AI Lab</Text></TouchableOpacity></View>;
if(screen==='lab')return <ScrollView style={s.page}><Text style={s.title}>AI MODEL LAB</Text><Text style={s.section}>INSTALLED MODELS</Text><Text>{modelStatus('stylewell-4b')?'✓':'○'} StyleWell 4B · {modelStatus('stylewell-4b')?'Installed':'Not Installed'}</Text><Text style={s.section}>FUTURE MODELS</Text><Text>○ Qwen3-VL 2B · Not Installed</Text><Text>○ Qwen3-VL 8B · Not Installed</Text><Text style={s.note}>Future models are metadata-only and cannot be downloaded from this screen.</Text><Button title="Select Lab Photo" onPress={()=>pick(false)}/><Button title="Back" onPress={()=>setScreen('home')}/></ScrollView>;
return <ScrollView style={s.page}>{uri&&<Image source={{uri}} style={s.photo}/>}<Button title={busy?'Analyzing…':'Analyze'} disabled={busy} onPress={analyze}/><Button title="Retake" onPress={()=>pick(true)}/>{result&&<><Text style={s.title}>CLOTHING ANALYSIS</Text>{attrs.map(a=><View key={a}><Text style={s.label}>{a}</Text><Text>{Array.isArray(result[a])?result[a].join(', '):(result[a]??'Unknown')}</Text><TextInput placeholder="Correct value (optional)" onChangeText={v=>setCorrections({...corrections,[a]:v})} onEndEditing={()=>saveCorrection(a)} style={s.input}/></View>)}<Text style={s.section}>Model</Text><Text>Qwen3-VL 2B · {result.inferenceTimeMs} ms</Text><Text style={s.section}>Raw AI response</Text><Text selectable>{result.rawResponse}</Text></>}<Button title="Home" onPress={()=>setScreen('home')}/></ScrollView>}
const s=StyleSheet.create({page:{flex:1,padding:24,paddingTop:70,backgroundColor:'#faf8f3'},title:{fontSize:28,fontWeight:'700',marginBottom:8},sub:{marginBottom:28,color:'#666'},section:{fontSize:18,fontWeight:'700',marginTop:24,marginBottom:8},link:{color:'#6b4eff',marginTop:28,textAlign:'center'},photo:{width:'100%',height:300,resizeMode:'contain',marginBottom:16},label:{fontWeight:'700',textTransform:'capitalize',marginTop:14},input:{borderWidth:1,borderColor:'#ddd',padding:8,marginTop:4,borderRadius:6},note:{color:'#666',marginBottom:20}});
