import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Button, FlatList, Image, KeyboardAvoidingView, Platform, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { API_CONFIGURED, API_URL, ClothingItem, Outfit, OutfitGeneration, analyzePhoto, deleteWardrobeItem, friendlyApiError, generateOutfit, getHealth, getModels, getOutfit, getOutfits, getWardrobe, imageUrl, rateOutfit, replaceOutfitItem, saveCorrection, saveOutfit, saveWardrobeItem, updateWardrobeItem } from './src/api';

const attributes = ['category', 'type', 'color', 'pattern', 'fabric', 'fit', 'style', 'occasion', 'season'];
const categoryFilters = ['All', 'Tops', 'Bottoms', 'Shoes', 'Outerwear', 'Accessories'];
const categoryChoices = ['Top', 'Bottom', 'Shoes', 'Outerwear', 'Accessories'];
const colorChoices = ['Black', 'White', 'Navy', 'Blue', 'Brown', 'Gray', 'Green', 'Red', 'Beige'];
const patternChoices = ['Solid', 'Striped', 'Plaid', 'Graphic', 'Floral', 'Printed'];
const fabricChoices = ['Cotton', 'Denim', 'Wool', 'Leather', 'Linen', 'Synthetic', 'Knit'];
const fitChoices = ['Slim', 'Regular', 'Relaxed', 'Oversized'];
const clothingStyleChoices = ['Casual', 'Smart casual', 'Formal', 'Sporty', 'Minimal', 'Vintage', 'Streetwear'];
const clothingOccasionChoices = ['Everyday', 'Work', 'Formal', 'Travel', 'Workout', 'Outdoor'];
const clothingSeasonChoices = ['Spring', 'Summer', 'Fall', 'Winter', 'All season'];
const outfitOccasions = ['Any', 'Everyday', 'School', 'Date', 'Casual', 'Formal', 'Work', 'Party'];
const outfitStyles = ['Any', 'Casual', 'Smart Casual', 'Formal', 'Streetwear', 'Sporty', 'Classic', 'Minimal', 'Preppy'];
const outfitSeasons = ['Any', 'Spring', 'Summer', 'Fall', 'Winter'];

type Screen = 'wardrobe' | 'review' | 'detail' | 'edit' | 'lab' | 'outfits' | 'generate' | 'result' | 'outfitDetail' | 'outfitLab';
type Draft = Record<string, any>;
type Connection = { state: 'idle' | 'checking' | 'connected' | 'error'; detail?: string };

const arrayOrEmpty = (value: any) => Array.isArray(value) ? value : value ? [value] : [];
const draftFrom = (value: any): Draft => ({
  name: value?.name ?? '', brand: value?.brand ?? '', category: value?.category ?? '', type: value?.type ?? '', color: value?.color ?? '',
  secondaryColors: arrayOrEmpty(value?.secondaryColors), pattern: value?.pattern ?? '', fabric: value?.fabric ?? '', fit: value?.fit ?? '',
  style: arrayOrEmpty(value?.style), occasion: arrayOrEmpty(value?.occasion ?? value?.occasions), season: arrayOrEmpty(value?.season ?? value?.seasons),
});
const displayValue = (value: any) => Array.isArray(value) ? value.join(' · ') || 'Not detected' : value || 'Not detected';
const roleForItem = (item: ClothingItem) => {
  const text = `${item.category ?? ''} ${item.type ?? ''} ${item.name ?? ''}`.toLowerCase();
  if (/(shoe|sneaker|boot|loafer|sandal|heel|slipper)/.test(text)) return 'shoes';
  if (/(outerwear|jacket|coat|parka|blazer|cardigan|vest)/.test(text)) return 'outerwear';
  if (/(accessor|belt|hat|scarf|bag|watch|tie)/.test(text)) return 'accessory';
  if (/(bottom|pant|jean|short|skirt|trouser|chino)/.test(text)) return 'bottom';
  if (/(top|shirt|tee|t-shirt|polo|blouse|sweater|hoodie|tank)/.test(text)) return 'top';
  return undefined;
};

function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) {
  return <TouchableOpacity onPress={onPress} hitSlop={{ top: 4, bottom: 4, left: 2, right: 2 }} style={[s.chip, selected && s.chipSelected]}><Text style={selected ? s.chipTextSelected : s.chipText}>{label}</Text></TouchableOpacity>;
}

function WardrobeImage({ imageId, variant = 'thumbnail', style }: { imageId: string; variant?: 'thumbnail' | 'original'; style: any }) {
  const [failed, setFailed] = useState(false);
  if (!imageId || failed) return <View style={[style, s.imageFallback]}><Text style={s.imageFallbackText}>{imageId ? 'Photo unavailable' : 'Test item'}</Text></View>;
  return <Image source={{ uri: imageUrl(imageId, variant) }} style={style} onError={() => setFailed(true)} />;
}

function OutfitItemCard({ item, onReplace, missing = false }: { item: ClothingItem; onReplace?: () => void; missing?: boolean }) {
  return <View style={s.outfitItemCard}><WardrobeImage imageId={item.imageId} style={s.outfitImage} /><View style={s.outfitItemText}><Text style={s.itemRole}>{(roleForItem(item) ?? 'item').toUpperCase()}</Text><Text style={s.outfitItemName} numberOfLines={2}>{item.name}</Text><Text style={s.cardMeta} numberOfLines={2}>{displayValue(item.color)} · {displayValue(item.style)}</Text>{missing ? <Text style={s.errorText}>This item was deleted</Text> : null}{onReplace ? <Button title="Replace" onPress={onReplace} /> : null}</View></View>;
}

export default function App() {
  const [screen, setScreen] = useState<Screen>('wardrobe');
  const [items, setItems] = useState<ClothingItem[]>([]);
  const [selected, setSelected] = useState<ClothingItem>();
  const [uri, setUri] = useState<string>();
  const [result, setResult] = useState<any>();
  const [draft, setDraft] = useState<Draft>({});
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('All');
  const [loading, setLoading] = useState(false);
  const [wardrobeError, setWardrobeError] = useState('');
  const [busy, setBusy] = useState(false);
  const [stage, setStage] = useState('');
  const [analysisError, setAnalysisError] = useState('');
  const [saveError, setSaveError] = useState('');
  const [saveBusy, setSaveBusy] = useState(false);
  const [labMode, setLabMode] = useState(false);
  const [corrections, setCorrections] = useState<Record<string, string>>({});
  const [connection, setConnection] = useState<Connection>({ state: 'idle' });
  const [models, setModels] = useState<any[]>([]);
  const [modelsLoading, setModelsLoading] = useState(false);
  const [modelsError, setModelsError] = useState('');
  const [outfits, setOutfits] = useState<Outfit[]>([]);
  const [outfitsError, setOutfitsError] = useState('');
  const [outfitLoading, setOutfitLoading] = useState(false);
  const [outfitResult, setOutfitResult] = useState<OutfitGeneration>();
  const [selectedOutfit, setSelectedOutfit] = useState<Outfit>();
  const [outfitOccasion, setOutfitOccasion] = useState('Any');
  const [outfitStyle, setOutfitStyle] = useState('Any');
  const [outfitSeason, setOutfitSeason] = useState('Any');
  const [anchorItem, setAnchorItem] = useState<ClothingItem>();
  const [recentCombinations, setRecentCombinations] = useState<string[]>([]);
  const [replaceRole, setReplaceRole] = useState<string>();
  const [testLab, setTestLab] = useState(false);

  const refreshWardrobe = async () => { setLoading(true); try { setItems(await getWardrobe(search, category)); setWardrobeError(''); } catch (error) { setWardrobeError(friendlyApiError(error)); } finally { setLoading(false); } };
  const refreshOutfits = async () => { setOutfitLoading(true); try { setOutfits(await getOutfits()); setOutfitsError(''); } catch (error) { setOutfitsError(friendlyApiError(error)); } finally { setOutfitLoading(false); } };
  useEffect(() => { if ((screen === 'wardrobe' || screen === 'generate') && API_CONFIGURED) { const timer = setTimeout(refreshWardrobe, 250); return () => clearTimeout(timer); } }, [screen, search, category]);
  useEffect(() => { if (screen === 'outfits' && API_CONFIGURED) refreshOutfits(); }, [screen]);
  useEffect(() => { if (screen !== 'lab' || !API_CONFIGURED) return; setModelsLoading(true); setModelsError(''); getModels().then(setModels).catch(error => setModelsError(friendlyApiError(error))).finally(() => setModelsLoading(false)); }, [screen]);

  const pick = async (camera = false, fromLab = false) => { const permission = camera ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert('Permission needed', 'Allow photo access in iPhone Settings.'); const selection = camera ? await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: 0.9 }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.9 }); if (!selection.canceled) { setUri(selection.assets[0].uri); setResult(undefined); setDraft({}); setAnalysisError(''); setSaveError(''); setLabMode(fromLab); setScreen('review'); } };
  const analyze = async () => { if (!uri) return; setBusy(true); setAnalysisError(''); setStage('Uploading photo…'); try { setStage('Analyzing your clothing locally…'); const analysis = await analyzePhoto(uri); setResult(analysis); setDraft(draftFrom(analysis)); setStage(''); } catch (error) { setAnalysisError(friendlyApiError(error)); setStage(''); } finally { setBusy(false); } };
  const testConnection = async () => { setConnection({ state: 'checking' }); try { const health = await getHealth(); setConnection({ state: 'connected', detail: `${health.modelName} · ${health.modelCached ? 'Model cached locally' : 'Model cache not found'}` }); } catch (error) { setConnection({ state: 'error', detail: friendlyApiError(error) }); } };
  const saveNewItem = async () => { if (!result || saveBusy) return; setSaveBusy(true); setSaveError(''); try { await saveWardrobeItem({ ...draft, imageId: result.imageId, modelId: result.modelId, modelVersion: result.modelVersion, confidence: result.confidence, rawResponse: result.rawResponse, inferenceTimeMs: result.inferenceTimeMs, parseSuccess: result.parseSuccess }); setScreen('wardrobe'); Alert.alert('Added to wardrobe.', 'Your clothing item is ready to browse.'); refreshWardrobe().catch(() => undefined); } catch (error) { setSaveError(friendlyApiError(error)); } finally { setSaveBusy(false); } };
  const saveItemEdits = async () => { if (!selected || saveBusy) return; setSaveBusy(true); setSaveError(''); try { const updated = await updateWardrobeItem(selected.id, draft); setSelected(updated); setScreen('detail'); refreshWardrobe().catch(() => undefined); } catch (error) { setSaveError(friendlyApiError(error)); } finally { setSaveBusy(false); } };
  const confirmDelete = () => { if (!selected) return; Alert.alert('Delete clothing item?', 'The saved wardrobe record will be removed. Your original image and analysis history will remain available.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { await deleteWardrobeItem(selected.id); setItems(current => current.filter(item => item.id !== selected.id)); setSelected(undefined); setScreen('wardrobe'); refreshWardrobe().catch(() => undefined); } catch (error) { Alert.alert('Delete failed', friendlyApiError(error)); } } }]); };
  const updateDraft = (key: string, value: any) => setDraft(current => ({ ...current, [key]: value }));
  const toggleDraftArray = (key: string, value: string) => updateDraft(key, arrayOrEmpty(draft[key]).includes(value) ? arrayOrEmpty(draft[key]).filter((item: string) => item !== value) : [...arrayOrEmpty(draft[key]), value]);
  const renderChoice = (label: string, key: string, choices: string[]) => <View><Text style={s.fieldLabel}>{label}</Text><View style={s.chips}>{choices.map(choice => <Chip key={choice} label={choice} selected={draft[key] === choice} onPress={() => updateDraft(key, choice)} />)}</View><TextInput value={draft[key] ?? ''} onChangeText={value => updateDraft(key, value)} placeholder={`Enter ${label.toLowerCase()} if needed`} style={s.input} /></View>;
  const renderMultiChoice = (label: string, key: string, choices: string[]) => <View><Text style={s.fieldLabel}>{label}</Text><View style={s.chips}>{choices.map(choice => <Chip key={choice} label={choice} selected={arrayOrEmpty(draft[key]).includes(choice)} onPress={() => toggleDraftArray(key, choice)} />)}</View></View>;
  const renderEditor = () => <View><Text style={s.fieldLabel}>Name</Text><TextInput value={draft.name ?? ''} onChangeText={value => updateDraft('name', value)} placeholder="e.g. Navy Polo" style={s.input} /><Text style={s.fieldLabel}>Brand (optional)</Text><TextInput value={draft.brand ?? ''} onChangeText={value => updateDraft('brand', value)} placeholder="Add manually if known" style={s.input} />{renderChoice('Category', 'category', categoryChoices)}<Text style={s.fieldLabel}>Type</Text><TextInput value={draft.type ?? ''} onChangeText={value => updateDraft('type', value)} placeholder="e.g. polo, jeans, boots" style={s.input} />{renderChoice('Color', 'color', colorChoices)}{renderChoice('Pattern', 'pattern', patternChoices)}{renderChoice('Fabric', 'fabric', fabricChoices)}{renderChoice('Fit', 'fit', fitChoices)}{renderMultiChoice('Style', 'style', clothingStyleChoices)}{renderMultiChoice('Occasions', 'occasion', clothingOccasionChoices)}{renderMultiChoice('Seasons', 'season', clothingSeasonChoices)}</View>;
  const renderGuidance = () => <View style={s.guidance}><Text style={s.guidanceTitle}>Photo tips</Text><Text>• Lay the item flat or hang it up.</Text><Text>• Make sure the entire item is visible.</Text><Text>• Use good lighting and avoid other clothing in frame.</Text></View>;

  const runGeneration = async (regenerate = false, sourceOverride?: 'wardrobe' | 'test', destination: Screen = 'result') => { setOutfitLoading(true); try { const generated = await generateOutfit({ occasion: outfitOccasion === 'Any' ? null : outfitOccasion, style: outfitStyle === 'Any' ? null : outfitStyle, season: outfitSeason === 'Any' ? null : outfitSeason, anchorItemId: anchorItem?.id ?? null, excludeCombinationIds: regenerate ? recentCombinations : [], source: sourceOverride ?? (testLab ? 'test' : 'wardrobe'), debug: true }); setOutfitResult(generated); if (generated.combinationId) setRecentCombinations(current => [...current.filter(id => id !== generated.combinationId), generated.combinationId!].slice(-6)); setScreen(destination); } catch (error) { Alert.alert('Could not generate outfit', friendlyApiError(error)); } finally { setOutfitLoading(false); } };
  const saveGeneratedOutfit = async () => { if (!outfitResult?.available || testLab) return; setSaveBusy(true); try { const saved = await saveOutfit({ name: `${outfitStyle === 'Any' ? 'New' : outfitStyle} Outfit`, clothingItemIds: outfitResult.clothingItemIds, occasion: outfitOccasion === 'Any' ? null : outfitOccasion, style: outfitStyle === 'Any' ? null : outfitStyle, season: outfitSeason === 'Any' ? null : outfitSeason, generationMethod: 'deterministic', generationMetadata: { score: outfitResult.score, combinationId: outfitResult.combinationId, explanation: outfitResult.explanation } }); setSelectedOutfit(saved); setScreen('outfitDetail'); Alert.alert('Outfit saved', 'You can find it in Saved Outfits.'); } catch (error) { Alert.alert('Could not save outfit', friendlyApiError(error)); } finally { setSaveBusy(false); } };
  const updateGeneratedItem = (role: string, item: ClothingItem) => { if (!outfitResult) return; const next = outfitResult.items.map(existing => roleForItem(existing) === role ? item : existing); setOutfitResult({ ...outfitResult, items: next, clothingItemIds: next.map(itemValue => itemValue.id), combinationId: next.map(itemValue => itemValue.id).sort().join('|') }); setReplaceRole(undefined); };
  const replacementChoices = useMemo(() => replaceRole ? items.filter(item => roleForItem(item) === replaceRole && !selectedOutfit?.clothingItemIds.includes(item.id)) : [], [replaceRole, items, selectedOutfit]);

  const renderWardrobe = () => <SafeAreaView style={s.shell}><FlatList data={items} numColumns={2} keyExtractor={item => item.id} style={s.list} contentContainerStyle={s.listContent} ListHeaderComponent={<View><Text style={s.title}>MY WARDROBE</Text><Text style={s.sub}>Your digital closet</Text><TouchableOpacity style={s.primaryButton} onPress={() => { setUri(undefined); setResult(undefined); setLabMode(false); setScreen('review'); }}><Text style={s.primaryButtonText}>＋ ADD CLOTHING</Text></TouchableOpacity><TouchableOpacity style={s.secondaryButton} onPress={() => setScreen('outfits')}><Text style={s.secondaryButtonText}>OUTFITS · GET DRESSED</Text></TouchableOpacity><TextInput value={search} onChangeText={setSearch} placeholder="Search color, type, style…" style={s.search} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filterRow}>{categoryFilters.map(filter => <Chip key={filter} label={filter} selected={category === filter} onPress={() => setCategory(filter)} />)}</ScrollView></View>} renderItem={({ item }) => <TouchableOpacity style={s.card} onPress={() => { setSelected(item); setScreen('detail'); }}><WardrobeImage imageId={item.imageId} style={s.cardImage} /><Text style={s.cardName} numberOfLines={1}>{item.name}</Text><Text style={s.cardMeta} numberOfLines={1}>{displayValue(item.color)}</Text></TouchableOpacity>} ListEmptyComponent={<View style={s.empty}>{loading ? <Text style={s.emptyTitle}>Loading wardrobe…</Text> : wardrobeError ? <><Text style={s.emptyTitle}>Wardrobe unavailable</Text><Text style={s.errorText}>{wardrobeError}</Text><Button title="Retry" onPress={refreshWardrobe} /></> : <><Text style={s.emptyTitle}>Your wardrobe is empty.</Text><Text style={s.emptyText}>Add your first clothing item to start building your digital closet.</Text><Button title="Add First Clothing Item" onPress={() => setScreen('review')} /></>}</View>} ListFooterComponent={<TouchableOpacity onPress={() => setScreen('lab')}><Text style={s.link}>Developer AI Lab</Text></TouchableOpacity>} /></SafeAreaView>;

  const renderReview = () => <SafeAreaView style={s.shell}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={s.scrollContent} keyboardDismissMode="interactive" keyboardShouldPersistTaps="handled"><Text style={s.title}>{labMode ? 'AI MODEL LAB' : 'ADD CLOTHING'}</Text>{!uri && <>{renderGuidance()}<Button title="Take Photo" onPress={() => pick(true)} /><Button title="Choose From Photos" onPress={() => pick(false)} /><Button title="Back to Wardrobe" onPress={() => setScreen('wardrobe')} /></>}{uri && <><Image source={{ uri }} style={s.photo} />{renderGuidance()}{!result && <Button title={busy ? stage : 'Analyze'} disabled={busy} onPress={analyze} />}{busy && <Text style={s.stage}>{stage}</Text>}{analysisError && <View style={s.errorBox}><Text style={s.errorText}>{analysisError}</Text><Button title="Try Again" onPress={analyze} /><Button title="Retake Photo" onPress={() => pick(true, labMode)} /><Button title="Cancel" onPress={() => setScreen(labMode ? 'lab' : 'wardrobe')} /></View>}{result && <><Text style={s.section}>{labMode ? 'ANALYSIS RESULT' : 'REVIEW BEFORE SAVING'}</Text>{result.qualityWarnings?.length > 0 && <View style={s.warningBox}><Text style={s.warningText}>Photo feedback: {result.qualityWarnings.join(' · ')}</Text></View>}{renderEditor()}{!labMode && <><Button title={saveBusy ? 'Saving…' : 'SAVE TO WARDROBE'} disabled={saveBusy} onPress={saveNewItem} />{saveError ? <Text style={s.errorText}>{saveError}</Text> : null}</>}{labMode && <><Text style={s.section}>Correction playground</Text>{attributes.map(attribute => <View key={attribute}><Text style={s.label}>{attribute}</Text><Text>{displayValue(result[attribute])}</Text><TextInput placeholder="Correct value (optional)" value={corrections[attribute] ?? ''} onChangeText={value => setCorrections({ ...corrections, [attribute]: value })} onEndEditing={async () => { if (corrections[attribute]) { try { await saveCorrection(result.imageId, attribute, result[attribute], corrections[attribute]); Alert.alert('Saved', 'Your correction was preserved.'); } catch (error) { Alert.alert('Correction not saved', friendlyApiError(error)); } } }} style={s.input} /></View>)}</>}{labMode && <Text selectable style={s.raw}>{result.rawResponse}</Text>}<Button title={labMode ? 'Back to AI Lab' : 'Retake Photo'} onPress={() => labMode ? setScreen('lab') : pick(true)} /><Button title="Back to Wardrobe" onPress={() => setScreen('wardrobe')} /></>}</>}</ScrollView></KeyboardAvoidingView></SafeAreaView>;

  const renderDetail = () => selected ? <SafeAreaView style={s.shell}><ScrollView contentContainerStyle={s.scrollContent}><WardrobeImage imageId={selected.imageId} variant="original" style={s.detailImage} /><Text style={s.title}>{selected.name}</Text>{selected.brand ? <Text style={s.sub}>{selected.brand}</Text> : null}{[['Category', selected.category], ['Type', selected.type], ['Color', selected.color], ['Pattern', selected.pattern], ['Fabric', selected.fabric], ['Fit', selected.fit], ['Style', selected.style], ['Occasions', selected.occasion], ['Seasons', selected.season]].map(([label, value]) => <View key={String(label)} style={s.detailRow}><Text style={s.detailLabel}>{label}</Text><Text>{displayValue(value)}</Text></View>)}<Text style={s.section}>AI DETAILS</Text><Text>Model: {selected.aiModelVersion}</Text><Text>Confidence: {Object.entries(selected.aiConfidence ?? {}).filter(([, value]) => value != null).map(([key, value]) => `${key} ${Math.round(Number(value) * 100)}%`).join(' · ') || 'Not provided'}</Text><Text style={s.note}>Created: {selected.createdAt}</Text>{selected.userCorrected && <Text style={s.corrected}>Includes user corrections</Text>}<Button title="BUILD AN OUTFIT AROUND THIS" onPress={() => { setAnchorItem(selected); setTestLab(false); setScreen('generate'); }} /><Button title="EDIT" onPress={() => { setDraft(draftFrom(selected)); setSaveError(''); setScreen('edit'); }} /><Button title="DELETE" color="#b42318" onPress={confirmDelete} /><Button title="Back to Wardrobe" onPress={() => setScreen('wardrobe')} /></ScrollView></SafeAreaView> : null;
  const renderEdit = () => <SafeAreaView style={s.shell}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={s.scrollContent} keyboardShouldPersistTaps="handled"><Text style={s.title}>EDIT CLOTHING</Text>{renderEditor()}<Button title={saveBusy ? 'Saving…' : 'SAVE CHANGES'} disabled={saveBusy} onPress={saveItemEdits} />{saveError ? <Text style={s.errorText}>{saveError}</Text> : null}<Button title="Cancel" onPress={() => setScreen('detail')} /></ScrollView></KeyboardAvoidingView></SafeAreaView>;
  const renderLab = () => { const installed = models.filter(model => model.status === 'installed'); const future = models.filter(model => model.status !== 'installed'); return <SafeAreaView style={s.shell}><ScrollView contentContainerStyle={s.scrollContent}><Text style={s.title}>AI MODEL LAB</Text><Text style={s.section}>BACKEND CONNECTION</Text><Text selectable style={s.url}>{API_CONFIGURED ? API_URL : 'EXPO_PUBLIC_API_URL is not configured'}</Text><View style={s.statusRow}><View style={[s.dot, connection.state === 'connected' ? s.green : connection.state === 'error' ? s.red : s.gray]} /><Text>{connection.state === 'checking' ? 'Checking…' : connection.state === 'connected' ? 'Connected' : connection.state === 'error' ? 'Unable to connect' : 'Not tested'}</Text></View>{connection.detail ? <Text selectable style={s.note}>{connection.detail}</Text> : null}<Button title="Test Backend Connection" disabled={connection.state === 'checking'} onPress={testConnection} />{modelsError ? <Text style={s.errorText}>{modelsError}</Text> : null}<Text style={s.section}>INSTALLED MODELS</Text>{modelsLoading ? <Text>Loading model status…</Text> : installed.length ? installed.map(model => <Text key={model.id}>✓ {model.name} · Installed</Text>) : <Text>○ No installed model reported</Text>}<Text style={s.section}>FUTURE MODELS</Text>{modelsLoading ? <Text>Loading model status…</Text> : future.length ? future.map(model => <Text key={model.id}>○ {model.name} · Not Installed</Text>) : <Text>No future models reported</Text>}<Text style={s.note}>The outfit engine uses structured wardrobe data and never downloads another model.</Text><Button title="Open Developer Outfit Lab" onPress={() => { setTestLab(true); setAnchorItem(undefined); setScreen('outfitLab'); }} /><Button title="Select Lab Photo" onPress={() => pick(false, true)} /><Button title="Back to Wardrobe" onPress={() => setScreen('wardrobe')} /></ScrollView></SafeAreaView>; };

  const renderOutfitConfig = () => <SafeAreaView style={s.shell}><ScrollView contentContainerStyle={s.scrollContent}><Text style={s.title}>{testLab ? 'OUTFIT ENGINE LAB' : 'GET DRESSED'}</Text><Text style={s.sub}>{anchorItem ? `Building around ${anchorItem.name}` : 'Choose a few preferences. The engine uses only saved wardrobe items.'}</Text><Text style={s.fieldLabel}>Occasion</Text><View style={s.chips}>{outfitOccasions.map(value => <Chip key={value} label={value} selected={outfitOccasion === value} onPress={() => setOutfitOccasion(value)} />)}</View><Text style={s.fieldLabel}>Style</Text><View style={s.chips}>{outfitStyles.map(value => <Chip key={value} label={value} selected={outfitStyle === value} onPress={() => setOutfitStyle(value)} />)}</View><Text style={s.fieldLabel}>Season</Text><View style={s.chips}>{outfitSeasons.map(value => <Chip key={value} label={value} selected={outfitSeason === value} onPress={() => setOutfitSeason(value)} />)}</View>{!testLab && <><Text style={s.fieldLabel}>Build around a specific item</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}><Chip label="Any item" selected={!anchorItem} onPress={() => setAnchorItem(undefined)} />{items.map(item => <Chip key={item.id} label={item.name} selected={anchorItem?.id === item.id} onPress={() => setAnchorItem(item)} />)}</ScrollView></>}<TouchableOpacity style={s.primaryButton} onPress={() => runGeneration(false)} disabled={outfitLoading}><Text style={s.primaryButtonText}>{outfitLoading ? 'BUILDING…' : 'GENERATE OUTFIT'}</Text></TouchableOpacity><Button title={testLab ? 'Back to AI Lab' : 'Back to Outfits'} onPress={() => setScreen(testLab ? 'lab' : 'outfits')} /></ScrollView></SafeAreaView>;
  const renderScore = (generation: OutfitGeneration) => generation.score ? <View style={s.scoreBox}><Text style={s.section}>WHY THIS OUTFIT</Text><Text style={s.scoreTotal}>{generation.score.total}/100</Text>{Object.entries(generation.score.components).map(([key, value]) => <View key={key} style={s.scoreRow}><Text style={s.scoreLabel}>{key}</Text><Text>{value}/10</Text></View>)}{generation.score.reasons?.length ? <Text style={s.note}>Notes: {generation.score.reasons.join(' · ')}</Text> : null}</View> : null;
  const renderResult = () => { if (!outfitResult) return null; return <SafeAreaView style={s.shell}><ScrollView contentContainerStyle={s.scrollContent}><Text style={s.title}>YOUR OUTFIT</Text><Text style={s.sub}>{outfitResult.isComplete ? 'A complete look from your wardrobe' : 'Best available from your wardrobe'}</Text>{outfitResult.items.map(item => <OutfitItemCard key={item.id} item={item} onReplace={() => setReplaceRole(roleForItem(item))} />)}{outfitResult.missingRoles?.length ? <View style={s.warningBox}><Text style={s.warningText}>Missing: {outfitResult.missingRoles.join(' · ')}</Text><Text>Add more items to complete this outfit.</Text></View> : null}<Text style={s.explanation}>{outfitResult.explanation}</Text><Text style={s.metaLine}>Occasion: {outfitOccasion} · Style: {outfitStyle} · Season: {outfitSeason}</Text>{renderScore(outfitResult)}{replaceRole && <View style={s.replaceBox}><Text style={s.section}>REPLACE {replaceRole.toUpperCase()}</Text>{items.filter(item => roleForItem(item) === replaceRole && !outfitResult.clothingItemIds.includes(item.id)).map(item => <TouchableOpacity key={item.id} style={s.replaceChoice} onPress={() => updateGeneratedItem(replaceRole, item)}><Text style={s.outfitItemName}>{item.name}</Text><Text>{displayValue(item.color)} · {displayValue(item.style)}</Text></TouchableOpacity>)}<Button title="Cancel" onPress={() => setReplaceRole(undefined)} /></View>}<TouchableOpacity style={s.primaryButton} onPress={() => runGeneration(true)} disabled={outfitLoading}><Text style={s.primaryButtonText}>{outfitLoading ? 'REGENERATING…' : '↻ REGENERATE'}</Text></TouchableOpacity>{!testLab && outfitResult.available && <Button title={saveBusy ? 'Saving…' : '♥ SAVE OUTFIT'} disabled={saveBusy} onPress={saveGeneratedOutfit} />}{testLab && <Text style={s.note}>Test wardrobe data is fictional and cannot be saved into your real wardrobe.</Text>}<Button title="Back to Generate" onPress={() => setScreen('generate')} /><Button title="Back to Outfits" onPress={() => setScreen('outfits')} /></ScrollView></SafeAreaView>; };
  const renderOutfits = () => <SafeAreaView style={s.shell}><ScrollView contentContainerStyle={s.scrollContent}><Text style={s.title}>OUTFITS</Text><Text style={s.sub}>Looks made from pieces you already own.</Text><TouchableOpacity style={s.primaryButton} onPress={() => { setTestLab(false); setAnchorItem(undefined); setScreen('generate'); }}><Text style={s.primaryButtonText}>＋ GENERATE OUTFIT</Text></TouchableOpacity>{outfitResult && <><Text style={s.section}>RECENTLY GENERATED</Text><TouchableOpacity style={s.recentCard} onPress={() => setScreen('result')}><Text style={s.outfitItemName}>{outfitResult.items.map(item => item.name).join(' · ') || 'No complete outfit yet'}</Text><Text>{outfitResult.score?.total ?? 0}/100 · Tap to view</Text></TouchableOpacity></>}{outfitsError ? <View style={s.errorBox}><Text style={s.errorText}>{outfitsError}</Text><Button title="Retry" onPress={refreshOutfits} /></View> : null}<Text style={s.section}>SAVED OUTFITS</Text>{outfitLoading ? <Text>Loading saved outfits…</Text> : outfits.length ? outfits.map(outfit => <TouchableOpacity key={outfit.id} style={s.savedCard} onPress={async () => { try { setSelectedOutfit(await getOutfit(outfit.id)); setScreen('outfitDetail'); } catch (error) { Alert.alert('Could not open outfit', friendlyApiError(error)); } }}><Text style={s.outfitItemName}>{outfit.name}</Text><Text>{outfit.clothingItems.map(item => item.name).join(' · ') || 'Some items unavailable'}</Text>{outfit.deletedItemIds.length ? <Text style={s.errorText}>{outfit.deletedItemIds.length} deleted item(s) need replacing</Text> : null}{outfit.userRating ? <Text>Rating: {outfit.userRating}/5</Text> : null}</TouchableOpacity>) : <Text style={s.emptyText}>No saved outfits yet. Generate one when you are ready.</Text>}<Button title="Back to Wardrobe" onPress={() => setScreen('wardrobe')} /></ScrollView></SafeAreaView>;
  const renderOutfitDetail = () => selectedOutfit ? <SafeAreaView style={s.shell}><ScrollView contentContainerStyle={s.scrollContent}><Text style={s.title}>{selectedOutfit.name}</Text><Text style={s.sub}>{selectedOutfit.occasion ?? 'Any occasion'} · {selectedOutfit.style ?? 'Any style'} · {selectedOutfit.season ?? 'Any season'}</Text>{selectedOutfit.clothingItems.map(item => <OutfitItemCard key={item.id} item={item} onReplace={() => setReplaceRole(roleForItem(item))} />)}{selectedOutfit.deletedItemIds.map(id => { const role = selectedOutfit.deletedItemRoles[id]; return <View key={id} style={s.warningBox}><Text style={s.warningText}>A saved item is no longer in the wardrobe.</Text><Text selectable>Missing item ID: {id}</Text>{role ? <Button title={`Replace missing ${role}`} onPress={() => setReplaceRole(role)} /> : <Text style={s.note}>The original role is unavailable; add a matching item and edit the outfit from the API later.</Text>}</View>; })}{replaceRole && <View style={s.replaceBox}><Text style={s.section}>REPLACE {replaceRole.toUpperCase()}</Text>{replacementChoices.map(item => <TouchableOpacity key={item.id} style={s.replaceChoice} onPress={async () => { try { setSelectedOutfit(await replaceOutfitItem(selectedOutfit.id, replaceRole, item.id)); setReplaceRole(undefined); } catch (error) { Alert.alert('Could not replace item', friendlyApiError(error)); } }}><Text style={s.outfitItemName}>{item.name}</Text><Text>{displayValue(item.color)} · {displayValue(item.style)}</Text></TouchableOpacity>)}<Button title="Cancel" onPress={() => setReplaceRole(undefined)} /></View>}<Text style={s.explanation}>{selectedOutfit.generationMetadata?.explanation ?? 'Saved from your wardrobe.'}</Text><Text style={s.section}>RATE THIS OUTFIT</Text><View style={s.chips}>{[1, 2, 3, 4, 5].map(value => <Chip key={value} label={`${value} ★`} selected={selectedOutfit.userRating === value} onPress={async () => { try { setSelectedOutfit(await rateOutfit(selectedOutfit.id, value)); } catch (error) { Alert.alert('Could not save rating', friendlyApiError(error)); } }} />)}</View><Button title="Back to Outfits" onPress={() => setScreen('outfits')} /></ScrollView></SafeAreaView> : null;
  const renderOutfitLab = () => <SafeAreaView style={s.shell}><ScrollView contentContainerStyle={s.scrollContent}><Text style={s.title}>DEVELOPER OUTFIT LAB</Text><Text style={s.sub}>Deterministic fixture data for tuning compatibility and ranking. It never enters your real wardrobe.</Text><Text style={s.section}>TEST SCENARIO</Text><View style={s.chips}>{['Everyday', 'Formal', 'Summer', 'Winter'].map(value => <Chip key={value} label={value} selected={outfitOccasion === value || outfitSeason === value} onPress={() => { if (outfitSeasons.includes(value)) setOutfitSeason(value); else setOutfitOccasion(value); }} />)}</View><Button title="Generate Fixture Outfit" onPress={() => runGeneration(false, 'test', 'outfitLab')} />{outfitResult && <>{outfitResult.items.map(item => <OutfitItemCard key={item.id} item={item} />)}{renderScore(outfitResult)}<Text style={s.section}>REJECTED CANDIDATES</Text>{outfitResult.rejected?.length ? outfitResult.rejected.map(candidate => <View key={candidate.clothingItemId} style={s.rejected}><Text style={s.outfitItemName}>{candidate.name}</Text><Text>{candidate.reasons.join(' · ')}</Text></View>) : <Text>No rejected candidate reasons in this run.</Text>}<Text style={s.note}>Candidates: {outfitResult.candidates?.length ?? 0}. Generated from structured attributes; no additional AI inference.</Text></>}<Button title="Back to AI Lab" onPress={() => setScreen('lab')} /></ScrollView></SafeAreaView>;

  if (screen === 'wardrobe') return renderWardrobe();
  if (screen === 'detail') return renderDetail();
  if (screen === 'edit') return renderEdit();
  if (screen === 'lab') return renderLab();
  if (screen === 'outfits') return renderOutfits();
  if (screen === 'generate') return renderOutfitConfig();
  if (screen === 'result') return renderResult();
  if (screen === 'outfitDetail') return renderOutfitDetail();
  if (screen === 'outfitLab') return renderOutfitLab();
  return renderReview();
}

const s = StyleSheet.create({
  shell: { flex: 1, backgroundColor: '#faf8f3' }, flex: { flex: 1 }, list: { flex: 1 }, listContent: { padding: 20, paddingBottom: 48 }, scrollContent: { padding: 24, paddingBottom: 48 },
  title: { fontSize: 28, fontWeight: '700', marginBottom: 6, color: '#211f1c' }, sub: { marginBottom: 20, color: '#716b64' }, section: { fontSize: 18, fontWeight: '700', marginTop: 24, marginBottom: 10, color: '#211f1c' },
  primaryButton: { backgroundColor: '#211f1c', borderRadius: 8, padding: 14, alignItems: 'center', marginBottom: 12 }, primaryButtonText: { color: '#fff', fontWeight: '700' }, secondaryButton: { backgroundColor: '#e6ded3', borderRadius: 8, padding: 14, alignItems: 'center', marginBottom: 16 }, secondaryButtonText: { color: '#211f1c', fontWeight: '700' }, search: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e0d9d0', borderRadius: 8, padding: 12, marginBottom: 10 }, filterRow: { paddingBottom: 16 }, chip: { borderWidth: 1, borderColor: '#d8d0c7', borderRadius: 18, paddingHorizontal: 12, paddingVertical: 8, marginRight: 7, marginBottom: 7, backgroundColor: '#fff' }, chipSelected: { backgroundColor: '#211f1c', borderColor: '#211f1c' }, chipText: { color: '#514b45', fontSize: 13 }, chipTextSelected: { color: '#fff', fontSize: 13, fontWeight: '700' },
  card: { width: '48%', backgroundColor: '#fff', borderRadius: 10, marginBottom: 14, marginRight: '4%', overflow: 'hidden' }, cardImage: { width: '100%', height: 190, backgroundColor: '#eee8df', resizeMode: 'cover' }, imageFallback: { alignItems: 'center', justifyContent: 'center' }, imageFallbackText: { color: '#716b64', fontSize: 12 }, cardName: { fontWeight: '700', paddingHorizontal: 10, paddingTop: 9 }, cardMeta: { color: '#716b64', paddingHorizontal: 10, paddingBottom: 10, paddingTop: 3 }, empty: { alignItems: 'center', padding: 28, marginTop: 20 }, emptyTitle: { fontSize: 20, fontWeight: '700', textAlign: 'center', marginBottom: 8 }, emptyText: { color: '#716b64', textAlign: 'center', marginBottom: 18 }, link: { color: '#6b4eff', textAlign: 'center', marginTop: 18, padding: 12 }, guidance: { backgroundColor: '#f0ebe4', borderRadius: 10, padding: 14, marginVertical: 16 }, guidanceTitle: { fontWeight: '700', marginBottom: 6 }, photo: { width: '100%', height: 300, resizeMode: 'contain', marginBottom: 12, backgroundColor: '#eee8df' }, detailImage: { width: '100%', height: 380, resizeMode: 'contain', backgroundColor: '#eee8df', marginBottom: 18 },
  fieldLabel: { fontWeight: '700', textTransform: 'capitalize', marginTop: 16, marginBottom: 7 }, input: { borderWidth: 1, borderColor: '#d8d0c7', backgroundColor: '#fff', padding: 11, marginBottom: 5, borderRadius: 7 }, chips: { flexDirection: 'row', flexWrap: 'wrap' }, stage: { color: '#6b4eff', marginVertical: 14, textAlign: 'center' }, errorBox: { backgroundColor: '#fff0ef', borderRadius: 8, padding: 12, marginVertical: 14 }, errorText: { color: '#a3261a', marginVertical: 8 }, warningBox: { backgroundColor: '#fff8df', borderRadius: 8, padding: 12, marginBottom: 10 }, warningText: { color: '#735500' }, label: { fontWeight: '700', textTransform: 'capitalize', marginTop: 14 }, raw: { backgroundColor: '#f2eee8', padding: 10, marginVertical: 14 }, detailRow: { borderBottomWidth: 1, borderBottomColor: '#eee8df', paddingVertical: 11 }, detailLabel: { color: '#716b64', fontSize: 12, textTransform: 'uppercase', marginBottom: 3 }, corrected: { color: '#18864b', marginVertical: 10 }, note: { color: '#716b64', marginVertical: 10 }, url: { fontFamily: 'Courier', fontSize: 13, marginBottom: 12, flexShrink: 1 }, statusRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 }, dot: { width: 10, height: 10, borderRadius: 5 }, green: { backgroundColor: '#18864b' }, red: { backgroundColor: '#c4382b' }, gray: { backgroundColor: '#888' },
  outfitItemCard: { backgroundColor: '#fff', borderRadius: 10, overflow: 'hidden', marginBottom: 14 }, outfitImage: { width: '100%', height: 220, backgroundColor: '#eee8df', resizeMode: 'cover' }, outfitItemText: { padding: 12 }, itemRole: { color: '#716b64', fontSize: 11, fontWeight: '700', letterSpacing: 1 }, outfitItemName: { color: '#211f1c', fontWeight: '700', fontSize: 17, marginVertical: 4 }, explanation: { color: '#514b45', fontSize: 16, lineHeight: 23, backgroundColor: '#f0ebe4', padding: 14, borderRadius: 8, marginVertical: 12 }, metaLine: { color: '#716b64', marginVertical: 8 }, scoreBox: { backgroundColor: '#fff', borderRadius: 10, padding: 14, marginVertical: 12 }, scoreTotal: { fontSize: 28, fontWeight: '700', color: '#6b4eff', marginBottom: 8 }, scoreRow: { flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#eee8df', paddingVertical: 7 }, scoreLabel: { textTransform: 'capitalize' }, replaceBox: { backgroundColor: '#f0ebe4', borderRadius: 10, padding: 12, marginVertical: 12 }, replaceChoice: { backgroundColor: '#fff', borderRadius: 8, padding: 12, marginBottom: 8 }, savedCard: { backgroundColor: '#fff', borderRadius: 10, padding: 14, marginBottom: 10 }, recentCard: { backgroundColor: '#e6ded3', borderRadius: 10, padding: 14, marginBottom: 10 }, rejected: { backgroundColor: '#fff0ef', borderRadius: 8, padding: 12, marginBottom: 8 },
});
